# Generated by Django 2.2.2 on 2019-06-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Project_Manager',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='is_Approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='ID_Personnel',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
