# Generated by Django 2.2.2 on 2019-06-14 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Core', '0003_projectassignment_is_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Personnel')),
                ('ID_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
