# Generated by Django 2.2.2 on 2019-06-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_userpersonnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='CreateDate',
        ),
    ]
