# Generated by Django 2.2.2 on 2019-06-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_remove_projecttask_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='ID_Activity',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ID_Customer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='ID_Project',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='ID_Assignment',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='ID_Task',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='ID_Vendor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
