# Generated by Django 2.2.2 on 2019-06-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20190615_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='Description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ID_ProjectTask',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.ProjectTask'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='Location',
            field=models.CharField(choices=[('R', 'Remote'), ('O', 'Office'), ('C', 'Customer Site')], default='O', max_length=1),
        ),
        migrations.DeleteModel(
            name='DetailActivity',
        ),
    ]
