# Generated by Django 2.2.2 on 2019-06-13 23:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('ID_Activity', models.IntegerField(primary_key=True, serialize=False)),
                ('Activity_Date', models.DateField(unique=True)),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID_Customer', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('ID_Personnel', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=20)),
                ('Status', models.CharField(choices=[('E', 'Employee'), ('O', 'Outsource'), ('C', 'Contract')], default='E', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ID_Project', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('Description', models.TextField(blank=True)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('ID_Vendor', models.IntegerField(primary_key=True, serialize=False)),
                ('Vendor_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('ID_Task', models.IntegerField(primary_key=True, serialize=False)),
                ('Priority', models.CharField(choices=[('H', 'HIGH'), ('M', 'MEDIUM'), ('L', 'LOW')], default='M', max_length=10)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True)),
                ('Status', models.CharField(choices=[('OG', 'On-Going'), ('DN', 'Done'), ('PD', 'Pending')], default='OG', max_length=2)),
                ('PctComplete', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('PctWeight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('CreateDate', models.CharField(max_length=255)),
                ('Start_Date', models.DateField()),
                ('TargetFinish_Date', models.DateField()),
                ('Target_Duration', models.IntegerField(default=0)),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
                ('PIC', models.CharField(max_length=255)),
                ('Total_Mandays', models.IntegerField(default=0)),
                ('ID_Project', models.ForeignKey(on_delete=models.SET(0), to='ActivitySheet.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_Assignment', models.IntegerField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
                ('ID_Personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ActivitySheet.Personnel')),
                ('ID_Project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ActivitySheet.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DetailActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=500)),
                ('Location', models.CharField(choices=[('R', 'Remote'), ('O', 'Office'), ('C', 'Customer Site')], default='O', max_length=1)),
                ('PctTaskComplete', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Last_Update', models.DateTimeField(auto_now=True)),
                ('ID_Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActivitySheet.ActivityLog')),
                ('ID_ProjectTask', models.ForeignKey(on_delete=models.SET(0), to='ActivitySheet.ProjectTask')),
            ],
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ID_Assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActivitySheet.ProjectAssignment'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ID_Personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActivitySheet.Personnel'),
        ),
    ]
